# Generated by Django 4.0.4 on 2022-06-05 22:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0002_remove_registro_id_delete_id_delete_registro'),
    ]

    operations = [
        migrations.CreateModel(
            name='Id',
            fields=[
                ('idRegistro', models.IntegerField(primary_key=True, serialize=False, verbose_name='Id de registro')),
                ('Nombre', models.CharField(max_length=50, verbose_name='Nombre')),
            ],
        ),
        migrations.CreateModel(
            name='Registro',
            fields=[
                ('NombreP', models.CharField(max_length=6, primary_key=True, serialize=False, verbose_name='Nombre')),
                ('Edad', models.CharField(max_length=2, verbose_name='Edad')),
                ('Email', models.CharField(max_length=20, verbose_name='E-mail')),
                ('Telefono', models.CharField(max_length=9, verbose_name='Telefono')),
                ('Contrasena', models.CharField(max_length=20, verbose_name='Contrasena')),
                ('Id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.id')),
            ],
        ),
    ]
