# Generated by Django 4.0.4 on 2022-06-05 23:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='IdC',
        ),
        migrations.RemoveField(
            model_name='registro',
            name='Id',
        ),
        migrations.RemoveField(
            model_name='registroc',
            name='Id',
        ),
        migrations.DeleteModel(
            name='Id',
        ),
        migrations.DeleteModel(
            name='Registro',
        ),
        migrations.DeleteModel(
            name='RegistroC',
        ),
    ]
